### PR TITLE
add cayman-blog theme

### PR DESCRIPTION
**Pull request by lorepirri**
thanks!

### CODE REVIEW

**Comment by artemsheludko** [comment]
Thanks for adding Cayman Blog Theme. Great theme!

**Comment by lorepirri** [comment]
hi thanks for the merge,
I'm afraid there is another theme with the same name though, and the link goes to the other one http://jekyllthemes.ru/cayman-blog/

**Comment by artemsheludko** [comment]
Thank you for the notice, already fixed!

**Comment by lorepirri** [comment]
thank you for taking the time to fix it! awesome website

**Comment by artemsheludko** [comment]
You're welcome

**Pull request merged**
